name: 'Verify Secrets'
description: 'This action will verify all secrets used in yaml files are defined as github secrets.'
author: Chris Tallman
branding:
  icon: 'user'
  color: 'red'
inputs:
  secrets:  # id of input
    description: 'Github Secrets'
    required: true
runs:
  using: "composite"
  steps:
    - id: install-pipenv
      name: Install pipenv
      run: |
        if ! command -v pip3 &> /dev/null
        then
          sudo apt-get update
          sudo apt-get install python3-pip -y
        fi
      shell: bash

    - run: |
        pip3 install -r $GITHUB_ACTION_PATH/requirements.txt
        python3 $GITHUB_ACTION_PATH/check.py
      env:
        SECRETS: ${{ inputs.secrets }}
      shell: bash
      