name: 'Verify Secrets'
description: 'This action will verify all secrets used in yaml files are defined as github secrets.'
author: Chris Tallman
branding:
  icon: 'user'
  color: 'red'
inputs:
  secrets:  # id of input
    description: 'Github Secrets'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: |
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
        python3 $GITHUB_ACTION_PATH/check.py
      env:
        SECRETS: ${{ inputs.secrets }}
      shell: bash
      