name: Update Release Tag
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Release Tag
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/v2",
              sha: context.sha,
              force: true,
            });